### ISSUE TITLE
Утилита парсинга и загрузки новых данных в базу

### ISSUE THREAD

**Issue by LasTAD** [LasTAD/memorand#12]
**Is your feature request related to a problem? Please describe.**
Необходимо упростить и автоматизировать сбор данных для расширения базы фраз

**Describe the solution you'd like**
Утилита, способная парсить посты определенной группы и загружать их в базу.

**Comment by LerikaXP** [comment]
Я как пользователь хочу, чтобы расширение базы фраз осуществлялось через специальную утилиту для ускорения процесса наполнения базы данных.

**Comment by LasTAD** [comment]
Парсер фраз добавлен, загрузка и регистрация картинок добавлена.
