### ISSUE TITLE
Перевести хранение ресурсов на локальную базу данных

### ISSUE THREAD

**Issue by LasTAD** [LasTAD/memorand#13]
**Is your feature request related to a problem? Please describe.**
Нет возможности централизованного хранения ресурсов и поддержания их актуальности

**Describe the solution you'd like**
Имплементация встроенной бд типа SQLite

**Comment by LerikaXP** [comment]
Я как пользователь хочу, чтобы составляющие ресурсы (изображения, накладываемый текст) хранились в локальной базе данных для использования приложения без выхода в интернет.

**Comment by LasTAD** [comment]
Переход на SQLite выполнен успешно.
